spring.application.name=spring-boot-jpa-postgresql

# DB connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# h2 database
#spring.h2.console.enabled=true
# anytime create. but this is fixed url
#spring.datasource.url=jdbc:h2:mem:demo

# none,create,update,validate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# data.sql Excute
#1. Let Spring Boot automatically create tables
# never,always,embedded
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.session.jdbc.initialize-schema=always
# spring.session.store-type=jdbc

#2. Creating a table manually
# Directly execute the SQL script provided by Spring Session JDBC
#: Path: org/springframework/session/jdbc/schema-postgresql.sql
# (in the spring-session-jdbc JAR)

# log
logging.level.org.hibernate.orm.jdbc.bind=trace

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

# Disable cache during development
spring.thymeleaf.cache=false

# server port number
#server.port=8081