spring.application.name=spring-boot-jpa-postgresql

server.port=8081


# DB connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# create: Create a table when the application starts. 
# update: Maintain the existing table and reflect only changes.
# validate: Only validates the table structure.
# none: Do nothing.
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

#1. Let Spring Boot automatically create tables
# spring.session.store-type=jdbc

# always: Attempt to create schema every time the application starts.
# embedded: Created only when using an embedded DB
# never : do not create
spring.session.jdbc.initialize-schema=always

#2. Creating a table manually
# Directly execute the SQL script provided by Spring Session JDBC: Path: org/springframework/session/jdbc/schema-postgresql.sql (in the spring-session-jdbc JAR)

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

# Disable cache during development
spring.thymeleaf.cache=false
