spring.application.name=spring-boot-jpa-postgresql

# DB 연결 설정
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=yolo11ai
spring.datasource.driver-class-name=org.postgresql.Driver

# create: 애플리케이션 시작 시 테이블 생성. update: 기존 테이블을 유지하며 변경 사항만 반영. 
# validate: 테이블 구조를 검증만 함. 
# none: 아무 작업도 하지 않음.
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# 1. Spring Boot가 자동으로 테이블 생성하게 하기
# spring.session.store-type=jdbc

# always : 애플리케이션 시작 시 매번 스키마 생성 시도
# embedded : 내장 DB일 때만 생성
# never : 생성 안 함
spring.session.jdbc.initialize-schema=never

# 2. 수동으로 테이블 생성하기
# Spring Session JDBC가 제공하는 SQL 스크립트를 직접 실행: 경로: org/springframework/session/jdbc/schema-postgresql.sql (spring-session-jdbc JAR 안에 있음)

